language: python
python: 3.6

sudo: required
services: docker

install:
  - pip3 install -r requirements-test.txt

script:
  - python3 -m pytest -v --cov replayserver
  - python3 setup.py bdist

after_success:
  - coveralls
